ログイン・ログアウト
deBroglieeeen/DataQueen pull request #38
Opened 2023-03-05 07:47 UTC by riko-okubo

## ログイン
<img width="1706" alt="image" src="https://user-images.githubusercontent.com/81846197/222948453-aed3a038-a814-49ea-a2a3-f56c4f492684.png">

## ログアウト（右上）
<img width="1700" alt="image" src="https://user-images.githubusercontent.com/81846197/222948476-8df72ac9-2371-4e70-ad71-dbb22d905ea7.png">

2023-03-05 08:12 UTC, tomoyuki-hiranuma requested changes

2023-03-05 08:12 UTC, tomoyuki-hiranuma commented on src/components/Login/Login.tsx
> +        <PrimaryButton onClick={() => loginWithRedirect()}>ログイン</PrimaryButton>
ParimaryButtonは主張激しいから、優しい感じのデザインの方がよさそう

2023-03-05 08:12 UTC, tomoyuki-hiranuma commented on src/components/Logout/Logout.tsx
> +    <Link
デザインをLinkにしてほしいだけで、Linkとして扱うとアクセシビリティ悪いので、LinkにonClick入れるんじゃなくて、ButtonにしてデザインをLinkにする方がいい
```typescript
<Button
 ....デザイン入れる
 onClick={() => {logout({ hoge })}}
>
Logout
</Button
```

2023-03-05 08:12 UTC, tomoyuki-hiranuma commented on src/components/Header/Header.tsx
> +    <Flex padding={`40px`} paddingLeft={0}>
padding入れてから、resetするようなcssはパフォーマンス悪いので避けたい。
バチッと当ててから戻っちゃうイメージ。

2023-03-05 08:14 UTC, deBroglieeeen approved these changes
LGTM!

2023-03-07 00:51 UTC, riko-okubo commented on src/components/Login/Login.tsx
> +        <PrimaryButton onClick={() => loginWithRedirect()}>ログイン</PrimaryButton>
この色で良いみたいなのでとりあえず、このままにします。

2023-03-07 08:21 UTC, deBroglieeeen commented
@riko-okubo @tomoyuki-hiranuma 
クエリ取得後に横スクロールすると画面全体が動いてしまうので、以前のままにするかレイアウトを変えるか話し合いたいです。

When I scroll horizontally after getting a query, the entire screen moves, so I would like to discuss whether to leave it as before or change the layout.
![DataQueenfeature:Login-buttonRReview](https://user-images.githubusercontent.com/40916953/223364206-dad61de1-4be0-468e-bf70-6b8f348bb2e7.gif)

2023-03-07 12:58 UTC, tomoyuki-hiranuma requested changes
少し細かいけど🙏

2023-03-07 13:37 UTC, tomoyuki-hiranuma approved these changes
LGTM

2023-03-07 13:37 UTC, merged