SQL
deBroglieeeen/DataQueen pull request #40
Opened 2023-03-06 06:36 UTC by riko-okubo

2023-03-06 06:38 UTC, riko-okubo reviewed
![image](https://user-images.githubusercontent.com/81846197/223036718-7f889bfc-7a2a-4f16-956f-a87f57941bae.png)

2023-03-07 02:39 UTC, deBroglieeeen requested changes
スピード感良いです！

ファイル名がQueryResultBeforeだと意味が通りにくいかもしれません。今回作ったのはクエリ実行前の**表示画面**のはずなので今回のブランチ名のような命名が良いと思います。

Good speed!

If the file name is QueryResultBefore, it may be hard to make sense of it. I think it is better to name it like this branch name because what we created this time is supposed to be the **display screen** before the query is executed.

2023-03-10 02:58 UTC, deBroglieeeen commented
- DisplayBeforeQuery
- PreQueryDisplay
あたりどう？
@riko-okubo @tomoyuki-hiranuma

2023-03-12 04:20 UTC, tomoyuki-hiranuma commented
component名に機能の挙動の話を入れたくはないと思った
それでいうと

2023-03-12 08:09 UTC, deBroglieeeen commented
SuggestQueryGuideは？

2023-03-12 08:21 UTC, deBroglieeeen approved these changes
LGTM

2023-03-12 08:21 UTC, merged